
$features_to_disable = 
    'LegacyComponents',
    'DirectPlay',
    'SimpleTCP',
    # 'Windows-Identity-Foundation',
    'WCF-HTTP-Activation',
    'WCF-NonHTTP-Activation',
    'IIS-WebServerRole',
    'IIS-WebServer',
    'IIS-CommonHttpFeatures',
    'IIS-HttpErrors',
    'IIS-HttpRedirect',
    'IIS-ApplicationDevelopment',
    'IIS-Security',
    'IIS-RequestFiltering',
    'IIS-NetFxExtensibility',
    'IIS-NetFxExtensibility45',
    'IIS-HealthAndDiagnostics',
    'IIS-HttpLogging',
    'IIS-LoggingLibraries',
    'IIS-RequestMonitor',
    'IIS-HttpTracing',
    'IIS-URLAuthorization',
    'IIS-IPSecurity',
    'IIS-Performance',
    'IIS-HttpCompressionDynamic',
    'IIS-WebServerManagementTools',
    'IIS-ManagementScriptingTools',
    'IIS-IIS6ManagementCompatibility',
    'IIS-Metabase',
    'WAS-WindowsActivationService',
    'WAS-ProcessModel',
    'WAS-NetFxEnvironment',
    'WAS-ConfigurationAPI',
    'IIS-HostableWebCore',
    'WCF-HTTP-Activation45',
    'WCF-TCP-Activation45',
    'WCF-Pipe-Activation45',
    'WCF-MSMQ-Activation45',
    'IIS-StaticContent',
    'IIS-DefaultDocument',
    'IIS-DirectoryBrowsing',
    'IIS-WebDAV',
    'IIS-WebSockets',
    'IIS-ApplicationInit',
    'IIS-ASPNET',
    'IIS-ASPNET45',
    'IIS-ASP',
    'IIS-CGI',
    'IIS-ISAPIExtensions',
    'IIS-ISAPIFilter',
    'IIS-ServerSideIncludes',
    'IIS-CustomLogging',
    'IIS-BasicAuthentication',
    'IIS-HttpCompressionStatic',
    'IIS-ManagementConsole',
    'IIS-ManagementService',
    'IIS-WMICompatibility',
    'IIS-LegacyScripts',
    'IIS-LegacySnapIn',
    'IIS-FTPServer',
    'IIS-FTPSvc',
    'IIS-FTPExtensibility',
    'MSMQ-Container',
    'MSMQ-DCOMProxy',
    'MSMQ-Server',
    'MSMQ-ADIntegration',
    'MSMQ-HTTP',
    'MSMQ-Multicast',
    'MSMQ-Triggers',
    'IIS-CertProvider',
    'IIS-WindowsAuthentication',
    'IIS-DigestAuthentication',
    'IIS-ClientCertificateMappingAuthentication',
    'IIS-IISCertificateMappingAuthentication',
    'IIS-ODBCLogging',
    'MediaPlayback',
    'WindowsMediaPlayer',
    'DataCenterBridging',
    'SmbDirect',
    'TIFFIFilter',
    'NetFx4Extended-ASPNET45',
    'SMB1Protocol-Deprecation',
    'MultiPoint-Connector',
    'MultiPoint-Connector-Services',
    'MultiPoint-Tools',
    'Printing-XPSServices-Features',
    'TelnetClient',
    'Printing-Foundation-LPDPrintService',
    'Printing-Foundation-LPRPortMonitor',
    'Client-ProjFS',
    'Client-DeviceLockdown',
    'Client-EmbeddedShellLauncher',
    'Client-EmbeddedBootExp',
    'Client-EmbeddedLogon',
    'Client-KeyboardFilter',
    'Client-UnifiedWriteFilter',
    'ServicesForNFS-ClientOnly',
    'ClientForNFS-Infrastructure',
    'NFS-Administration',
    'HostGuardian',
    'Internet-Explorer-Optional-amd64',
    'AppServerClient',
    'Containers-DisposableClientVM',
    'Microsoft-Hyper-V-All',
    'Microsoft-Hyper-V',
    'Microsoft-Hyper-V-Tools-All',
    'Microsoft-Hyper-V-Management-PowerShell',
    'Microsoft-Hyper-V-Hypervisor',
    'Microsoft-Hyper-V-Services',
    'Microsoft-Hyper-V-Management-Clients',
    'DirectoryServices-ADAM-Client',
    'Windows-Defender-ApplicationGuard',
    'Containers',
    'SMB1Protocol',
    'SMB1Protocol-Client',
    'SMB1Protocol-Server';

foreach ($feature in $features_to_disable) {
    Disable-WindowsOptionalFeature -Online -Remove -NoRestart -FeatureName $feature
}

Get-WindowsOptionalFeature -Online |
Where-Object State -eq "Disabled" |
Select-Object FeatureName --ExpandProperty


$features_to_enable = 
    'MicrosoftWindowsPowerShellV2Root',
    'MicrosoftWindowsPowerShellV2',
    'Printing-PrintToPDFServices-Features',
    'VirtualMachinePlatform',
    'HypervisorPlatform',
    'Microsoft-Windows-Subsystem-Linux';
    
foreach ($feature in $features_to_enable) {
    Enable-WindowsOptionalFeature -Online -FeatureName $feature
}

Get-WindowsOptionalFeature -Online | 
Where-Object State -eq "Enabled" |
Select-Object FeatureName --ExpandProperty
